package com.safety.protocol;

import akka.actor.typed.ActorRef;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.Instant;

/**
 * InspecSafe V1 — Visual Inspection Protocol.
 *
 * Mirrors the InspecSafe-V1 HuggingFace dataset structure:
 *   - 5 industrial environments (tunnel, power, sintering, oil/gas, coal conveyor)
 *   - 7 anomaly categories derived from dataset annotations
 *   - 3-tier safety grading (Grade 1 = critical → Grade 3 = minor observation)
 *   - Robot MAC-style IDs and named waypoints
 *
 * Events are generated by VisualInspectionAgent and pushed to the HTTP server
 * for dashboard display. They use a separate severity track from the gas-sensor
 * T1/T2/T3 escalation pipeline.
 */
public class InspectionProtocol {

    // ── Environments ──────────────────────────────────────────────────────────
    public enum Environment {
        TUNNEL              ("Tunnel"),
        POWER_FACILITY      ("Power Facility"),
        SINTERING_EQUIPMENT ("Sintering Equipment"),
        OIL_GAS_PLANT       ("Oil/Gas Plant"),
        COAL_CONVEYOR       ("Coal Conveyor Gallery");

        public final String label;
        Environment(String label) { this.label = label; }
    }

    // ── Anomaly types (direct from dataset annotation folders) ────────────────
    public enum AnomalyType {
        NO_HELMET           ("No Safety Helmet",   "head"),
        NO_MASK             ("No Protective Mask", "nonmask"),
        NO_GLOVES           ("No Protective Gloves","nonmask"),
        FALL_DETECTED       ("Personnel Fall",     "fall"),
        FIRE_DETECTED       ("Open Flame / Fire",  "fire"),
        SMOKING             ("Smoking Violation",  "cigarette"),
        UNAUTHORIZED_VEHICLE("Unauthorized Vehicle","nonautomobile"),
        NORMAL              ("No Anomaly Detected", "normal");

        public final String label;
        public final String datasetCode;
        AnomalyType(String label, String datasetCode) {
            this.label = label;
            this.datasetCode = datasetCode;
        }
    }

    // ── Safety grading (InspecSafe annotation standard) ──────────────────────
    public enum SafetyGrade {
        GRADE_1 ("Grade One",   "Critical"),   // immediate hazard to life
        GRADE_2 ("Grade Two",   "Significant"),// policy violation / equipment risk
        GRADE_3 ("Grade Three", "Minor"),      // observation / near-miss
        NORMAL  ("Normal",      "Normal");     // compliant

        public final String label;
        public final String severity;
        SafetyGrade(String label, String severity) {
            this.label = label;
            this.severity = severity;
        }
    }

    // ── Event record — CborSerializable so it can cross Akka cluster nodes ───
    public record InspectionEvent(
        String      waypointId,    // e.g. "58132919741960_20251117_kv-switchgear-01"
        String      robotId,       // MAC-style robot identifier
        String      location,      // waypoint name / description
        Environment environment,
        AnomalyType anomalyType,
        SafetyGrade safetyGrade,
        String      description,   // semantic scene description (InspecSafe .txt format)
        String      imagePath,     // relative path to .jpg served by /api-inspection/image/
        String      audioPath,     // relative path to .wav served by /api-inspection/audio/ (null if unavailable)
        String      infraredPath,  // relative path to IR .mp4 served by /api-inspection/video/ (null if unavailable)
        // Cross-modal sensor readings from waypoint *_sensor_*.json (null if unavailable)
        Double      coReading,     // CO  concentration PPM  — carbon monoxide
        Double      ch4Level,      // CH4 concentration %VOL — methane (flammable gas)
        Double      o2Level,       // O2  concentration %VOL — oxygen (deficiency/enrichment)
        Double      h2sReading,    // H2S concentration PPM  — hydrogen sulphide (toxic)
        Double      temperature,   // °C from InspecSafe sensor log
        Double      humidity,      // % RH from InspecSafe sensor log
        Double      soundLevel,    // ambient sound level dB (simulated; real audio served via audioPath)
        Instant     timestamp
    ) implements CborSerializable {}

    // ── InspectionReceiverActor command — carries event across the cluster wire
    public interface ReceiverCommand extends CborSerializable {}
    public record ForwardInspectionEvent(@JsonProperty("event") InspectionEvent event) implements ReceiverCommand {}
}
