# Node A — ingestion + fusion (sensor shards, thermal, fusion, classification)

include "application.conf"

akka {
  remote.artery {
    canonical.hostname = ${safety.cluster.host-a}
    canonical.port = 2551
  }

  cluster {
    roles = ["ingestion", "fusion", "persistence"]
    min-nr-of-members = 2
  }
}
