# Node C — orchestrator + dashboard + MongoDB writer + HTTP server

include "application.conf"

akka {
  remote.artery {
    canonical.hostname = ${safety.cluster.host-bc}
    canonical.port = 2553
  }

  cluster {
    roles = ["orchestrator", "persistence", "dashboard"]
  }
}

safety.http.port = 8080
